### ISSUE TITLE
Mod does not work on a dedicated Linux server

### ISSUE THREAD

**Issue by Navatusein** [OCB7D2D/ElectricityOverhaul#1]
Good day. I tried to install your mod on the server but it refuses to work. I had an assumption that BepInEx won't start, but your mod https://github.com/OCB7D2D/ElectricityButtonsPush works fine. They seem to require BepInEx too. I installed BepInEx from your repository https://github.com/OCB7D2D/A20BepInExPreloader. Please tell me what could be wrong.

**Comment by mgreter** [comment]
Only the Overhaul Mod really needs BepInEx to work, the other mods just compile via my tools, but they have no runtime dependency on BepInEx. I didn't really try it much with A20 yet, so it might not work at all in multiplayer (primary goal was to port everything to A20 SP). Not sure if/when I get the time to investigate it further.

**Comment by mgreter** [comment]
I've added and tested linux compatibility today.
You will need to start client/server via a special startup script.
There is no other way for BepInEx to work in linux...
https://github.com/OCB7D2D/ElectricityOverhaul/archive/master.zip
There is no official new version yet, so please test it on master branch.
