### ISSUE TITLE
SMX Game Menu

### ISSUE THREAD

**Issue by BJR1984** [OCB7D2D/ElectricityOverhaul#13]
The power tab that you have implemented is not loading correctly.
I have made a issue with Sirillion as well.
[https://github.com/Sirillion/SMXhud/issues/4#issue-1376370231](url)
included full log.

WRN More tabs (5) than tab buttons (4) in newContinueGame

[output_log_client__2022-09-16__14-30-00.txt](https://github.com/OCB7D2D/ElectricityOverhaul/files/9586512/output_log_client__2022-09-16__14-30-00.txt)
![A20 6_2022-09-16_14-51-19](https://user-images.githubusercontent.com/18244897/190711075-bad37d52-65dc-4617-b3a5-7552111638b9.jpg)

**Comment by mgreter** [comment]
Have you tried it with the `ZMXuiCPOCBEO` patch?
[You need to copy this addon into the Mods folder](https://github.com/OCB7D2D/ElectricityOverhaul/tree/master/Addons/ZMXuiCPOCBEO).
But good chance stuff has already changed and regressed in the mean time ...

**Comment by BJR1984** [comment]
That patch doesn't work.

**Comment by mgreter** [comment]
Yep, seems I simply forgot to upgrade the patcher with that release, sorry about that.
Testing fix https://github.com/OCB7D2D/ElectricityOverhaul/tree/bugfix/xml-patcher now ...
