### ISSUE TITLE
Trying to install this on a server and getting an error

### ISSUE THREAD

**Issue by losthymns** [OCB7D2D/ElectricityOverhaul#15]
[output_log_07-20-13-12-2022.txt](https://github.com/OCB7D2D/ElectricityOverhaul/files/10217852/output_log_07-20-13-12-2022.txt)

Any help is appreciated, I'd like to use the mod but having some trouble installing it. Thank you.

**Comment by mgreter** [comment]
Are you trying to add the mod to an existing map?

=> https://github.com/OCB7D2D/ElectricityOverhaul#vanilla-map-loading

**Comment by losthymns** [comment]
So, sorry I'm a bit of a newb. Do I set it to false or true if I already have an existing world?

**Comment by mgreter** [comment]
If you are not sure what to do after carefully reading the linked paragraph, I would recommend to start with a new world. Otherwise make a Backup and start trying, and yes, the `LoadVanillaMap` must be set to true exactly once!
