### ISSUE TITLE
A21 issue

### ISSUE THREAD

**Issue by AstraMuun** [OCB7D2D/ElectricityOverhaul#19]
[output_log_client__2023-12-02__00-25-26.txt](https://github.com/OCB7D2D/ElectricityOverhaul/files/13537316/output_log_client__2023-12-02__00-25-26.txt)

Didnt have a problem before. Opened a new game to see how it works exactly, works just fine. Opened my actual save file with all my friends, and this keep happening. It only happens on the save file with my friends, if I open my solo map it works just fine.

**Comment by mgreter** [comment]
There is no version yet for A21, it's as simple as that, sorry.
