### ISSUE TITLE
How to set the degrading of the solar cells?

### ISSUE THREAD

**Issue by Shadow-Genesis** [OCB7D2D/ElectricityOverhaul#21]
As the subject line, I want to know how to change the degrading of the solar cells. Can anyone tell me how?

Sorry its not an issue, just don't know where else to ask.

**Comment by mgreter** [comment]
There is no specific option for "only" the solar cells, only in general:
![image](https://github.com/OCB7D2D/OcbElectricityOverhaul/assets/282293/ae08d874-0811-4d5a-8f72-25bb13abf1cc)
