### ISSUE TITLE
Minor issue with stable b14

### ISSUE THREAD

**Issue by sphinxlady** [OCB7D2D/ElectricityOverhaul#22]
![overhaul](https://github.com/user-attachments/assets/398966ac-63b3-427c-8d5d-74fb8ab797f9)

Nothing major seems to work fine otherwise.

**Comment by mgreter** [comment]
I would need an actual log, screenshot doesn't even indicate the error is from my mod

**Comment by mgreter** [comment]
Recompiled the mod against V1.1, hopefully that fixes it

**Comment by sphinxlady** [comment]
Fixed.

Nothing more the then a cosmetic issue from some minor icon updates on their part.
