### ISSUE TITLE
Version 1.2(b27) update needed - UI is broken

### ISSUE THREAD

**Issue by dwightdurmon** [OCB7D2D/ElectricityOverhaul#23]
Hello,

With the recently released 1.2 update, the OcbElectricityOverhaul mod is causing UI issues.  I tested this by only installing the OcbElectricityOverhaul mod and it causes the main menu screen to not load correctly.

The Main Menu looks like this when it tries to load.

![Screenshot 2024-12-10 181713](https://github.com/user-attachments/assets/997f429d-5177-4d76-849a-0e5e889283ea)

**Comment by dwightdurmon** [comment]
(google translate)

Hallo,

Mit dem kürzlich veröffentlichten Update 1.2 verursacht das Mod OcbElectricityOverhaul Probleme mit der Benutzeroberfläche. Ich habe dies getestet, indem ich nur das Mod OcbElectricityOverhaul installiert habe, und es führt dazu, dass der Hauptmenübildschirm nicht richtig geladen wird.

Das Hauptmenü sieht beim Laden so aus.

**Comment by mgreter** [comment]
Fixed by recompiling, version will be up soon on nexusmods
