### ISSUE TITLE
Linux dedicated server multiplayer

### ISSUE THREAD

**Issue by kroonstaar** [OCB7D2D/ElectricityOverhaul#7]
hey,

I just can't get it to work on my Linux server. Loading the same savegame in local singleplayer on windows seems to work fine but as soon as I run it on my server every client gets an "EndOfStreamException: Attempted to read past the end of the stream" when placing or interacting with generators etc.

Also, I can't use any properties in serverconfig.xml, as seen in this log:
```
2022-07-03T15:10:01 0.183 ERR ====================================================================================================
2022-07-03T15:10:01 0.183 ERR Error parsing configfile property 'LoadVanillaMap': Unknown config option
2022-07-03T15:10:01 0.183 INF Make sure your configfile is updated the current server version!
2022-07-03T15:10:01 0.183 INF Startup aborted due to the given error in server configfile
2022-07-03T15:10:01 0.183 ERR ====================================================================================================
```

Server is started via startmodserver.sh using version 20.5 (b2)

**Comment by mgreter** [comment]
Since the server doesn't know about the options I highly doubt the mod is loaded correctly.
Can you attach a full log here and also some detailed info how you start the server? thx!

**Comment by kroonstaar** [comment]
okay, I found my issue.
BepInEx was loaded so I thought everything should be loaded. Turns out only mods from the game root directory are loaded (at least with BepInEx) and not those located in AppData (~./local/share on Linux). After moving Electricity Overhaul to the game root/Mods everything works fine.
Sorry for opening the issue, but maybe add this to the readme?

nice mod btw, I really love it

**Comment by mgreter** [comment]
No problem and thanks for reporting back! I already have an eye open for the new mod location (guess I only checked that on windows), and I thought my mods are already compatible, but yes, for now I would recommend to stick to the old way. But will certainly try to make it compatible with either way (as far as possible).

**Comment by mgreter** [comment]
I guess that config doesn't really do much on linux and is the culprit:
https://github.com/OCB7D2D/ElectricityOverhaul/blob/master/BepInEx/doorstop_config.ini#L13-L14
```
[MultiFolderLoader_UserData]
baseDir = %APPDATA%\7DaysToDie\Mods
```
Any idea how this could be adjusted to also find the new location on linux?

**Comment by kroonstaar** [comment]
Only if you could specify more than one path I guess. As far as I know, there is no environment variable on Windows or Linux for that

**Comment by mgreter** [comment]
I guess that config somehow would support multiple directories.
But that is not even the point, as the above is obviously not valid for linux.
On linux, that setting needs to adjust to point to the new mod location there.
Guess you also say you don't know any reliable way to point to it then !?
I mean on windows it also just points to the default location ...

**Comment by kroonstaar** [comment]
The default location seems to be `~/.local/share/7DaysToDie/Mods`

**Comment by mgreter** [comment]
I may add some text to the readme to mention that edge case, thx!
Btw. you got it working on linux, right? Just wanting to add a "it works" to the list :)

**Comment by kroonstaar** [comment]
yes! working on Linux with version A20.5 b2
