### ISSUE TITLE
Battery are not being charged

### ISSUE THREAD

**Issue by Vincent-HD** [OCB7D2D/ElectricityOverhaul#8]
Hi, I'm having an issue with battery charging, I can't get them to work.
![image](https://user-images.githubusercontent.com/61592570/180672896-1eb48a7a-d4d7-4b67-acf3-d64a7402c78a.png)
![image](https://user-images.githubusercontent.com/61592570/180672913-04237f42-e127-4046-8e17-e55bd91caab7.png)
![image](https://user-images.githubusercontent.com/61592570/180672925-43ee4df6-660a-40c8-9e98-e7b17f1060ec.png)

Here are my mods from you:
![image](https://user-images.githubusercontent.com/61592570/180673061-d6ff8ce7-ae1a-4bb6-80b1-387f9fe048ca.png)

The only line that gives me info about the loading of mods is:
```
2022-07-24T23:20:13 0.868 INF Loading OCB Electricity Overhaul Patch: OcbElectricityOverhaul
Fallback handler could not load library C:/TCAFiles/Users/thibaulta/21080/7DaysToDieServer_Data/Mono/data-00000150F0210310.dll
```
Do you already see this kind of issue ? Where do you think can be the issue ?

**Comment by mgreter** [comment]
Did you enable it to allow to charge from generators. Otherwise I don't see much wrong (although can't tell if you connected generator to battery bank in the right direction). Can't really reproduce, my batteries just load fine.
![image](https://user-images.githubusercontent.com/282293/180681364-da525ae8-2c07-4f52-9a33-be52ab601dc6.png)
FWIW I can at least see from your screenshot that the generator knows that something down the line would like to be charged. Do you have any other mods running? Maybe try to remove wind power and workarounds too, just to make sure it isn't any compatibility issue. Other than that, not much I could do from here.

**Comment by Vincent-HD** [comment]
So, yes I have plenty of mods, but I don't have the "Charging from" box, I'm using SMX is it problematic ?
![image](https://user-images.githubusercontent.com/61592570/180701092-16bf5a5c-9fd9-4f8a-bf35-7799b78421fd.png)

There is the full modlist which lot of them are from CP48:
![image](https://user-images.githubusercontent.com/61592570/180701199-b9e2edcf-5510-422a-9ca6-97d4769ae5c9.png)

I'll try to install mod manager to disable one mod at the time to see what's wrong.

Btw do you have a tips when testing, how do you get used battery ? I need to wait until they are a little bit discharged just to test :D

**Comment by Vincent-HD** [comment]
Ok so, I tested in a singleplayer game, and it didn't work, so I started to unload all mods, with just electricity overhaul, and then I got the menu in singleplayer, I started to enable SMX, still the menu, then other mods but not CP48, still have menu and even with all mods I still have the menu, but as soon as I log into my server I don't have the menu anymore so its server side :/

I'll look little bit closer because I want this feature back :D

**Comment by Vincent-HD** [comment]
Also does those files matters for the mod to work ? I'm doubting that scripts files would be necessary but the .so i'm not sure.
My hosting provider disallow theses files extensions, those are failed transfer from filezilla.
![image](https://user-images.githubusercontent.com/61592570/180705543-0ef9b814-3478-4f6e-ba53-a08489eba02f.png)

**Comment by mgreter** [comment]
When connecting to a server it will send each client the xml from its own config (so clients basically ignore the local xml). By knowing that I would assume you did not install all necessary things on the server. The `.sh` and `.bat` files are not really needed (mostly), but the `.so` files are important if you are running a linux server, and if you do, you also need to follow: https://github.com/OCB7D2D/ElectricityOverhaul#linux-support
