### ISSUE TITLE
Wattage drawn incorrect on dedicated server

### ISSUE THREAD

**Issue by THS-Shiniri** [OCB7D2D/ElectricityOverhaul#9]
I´ve downloaded and installed the mod on my PC and Server. In Singleplayer the Wattage drawn is given correctly e.g. 10 Blade Traps draw 200W (180W by Solar Power & 20W by Batteries while the Gen has 0W)

On my Server 8 or 9 Turrets (each 15W) only draw 45ish Watts ? Any Idea? xD

**Comment by mgreter** [comment]
This sounds like you had a power reset bug in your gameplay.
One symptom of that bug is that all consumers get reset to use 5W.
Please re-open if you properly reproduce the bug.
